services:
  - type: web
    name: spoiler-signals-web
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: 8142201280:AAH9KCcOZXH5XvlvPOPKmvPMy9pKmgPqAFs
      - key: CHAT_ID
        value: -1002605021077

  - type: worker
    name: spoiler-signals-scan
    env: python
    plan: free
    buildCommand: ""
    startCommand: python scan_all.py
    envVars:
      - key: BOT_TOKEN
        value: 8142201280:AAH9KCcOZXH5XvlvPOPKmvPMy9pKmgPqAFs
      - key: CHAT_ID
        value: -1002605021077

  - type: worker
    name: spoiler-signals-check-tp
    env: python
    plan: free
    buildCommand: ""
    startCommand: python check_targets.py
    envVars:
      - key: BOT_TOKEN
        value: 8142201280:AAH9KCcOZXH5XvlvPOPKmvPMy9pKmgPqAFs
      - key: CHAT_ID
        value: -1002605021077
